MPA_Project_Juca_Oana/Controllers/CitiesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Policy;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MPA_Project_Juca_Oana.Data;
using MPA_Project_Juca_Oana.Models;
using MPA_Project_Juca_Oana.Models.ViewModels;

namespace MPA_Project_Juca_Oana.Controllers
{
    [Authorize(Policy = "OnlyPremium")]
    public class CitiesController : Controller
    {
        private readonly LibraryContext _context;

        public CitiesController(LibraryContext context)
        {
            _context = context;
        }

        // GET: Cities
        public async Task<IActionResult> Index(int? id, int? stadiumsID)
        {
            var viewModel = new CityIndexData();
            viewModel.City = await _context.City_1
            .Include(i => i.StadiumByCity)
                .ThenInclude(i => i.Stadium)
            .ThenInclude(i => i.Orders)
            .ThenInclude(i => i.Customers)
            .AsNoTracking()
            .OrderBy(i => i.CityName)
            .ToListAsync();
            if (id != null)
            {
                ViewData["CityID"] = id.Value;
                City cities = viewModel.City.Where(
                i => i.ID == id.Value).Single();
                viewModel.Stadiums = cities.StadiumByCity.Select(s => s.Stadium);
            }
            if (stadiumsID != null)
            {
                ViewData["StadiumsID"] = stadiumsID.Value;
                viewModel.Orders = viewModel.Stadiums.Where(
                x => x.ID == stadiumsID).Single().Orders;
            }
            return View(viewModel);
        }

        // GET: Cities/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.City_1 == null)
            {
                return NotFound();
            }

            var city = await _context.City_1
                .FirstOrDefaultAsync(m => m.ID == id);
            if (city == null)
            {
                return NotFound();
            }

            return View(city);
        }

        // GET: Cities/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Cities/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,CityName")] City city)
        {
            if (ModelState.IsValid)
            {
                _context.Add(city);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(city);
        }

        // GET: Cities/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            
                if (id == null)
                {
                    return NotFound();
                }
                var city = await _context.City_1
                .Include(i => i.StadiumByCity).ThenInclude(i => i.Stadium)
                .AsNoTracking()
                .FirstOrDefaultAsync(m => m.ID == id);
                if (city == null)
                {
                    return NotFound();
                }
                PopulateCityStadiumData(city);
                return View(city);

         }
            private void PopulateCityStadiumData(City city)
            {
                var allStadiums = _context.Stadiums;
                var cityStadium = new HashSet<int>(city.StadiumByCity.Select(c => c.StadiumID));
                var viewModel = new List<CityStadiumData>();
                foreach (var stad in allStadiums)
                {
                    viewModel.Add(new CityStadiumData
                    {
                        StadiumID = stad.ID,
                        Name = stad.Name,
                        LocatedInCity = cityStadium.Contains(stad.ID)
                    });
                }
                ViewData["Stadiums"] = viewModel;
            }
        

        // POST: Cities/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int? id, string[] selectedStadiums)
        {
            if (id ==null)
            {
                return NotFound();
            }
            var cityToUpdate = await _context.City_1
            .Include(i => i.StadiumByCity)
            .ThenInclude(i => i.Stadium)
            .FirstOrDefaultAsync(m => m.ID == id);
            if (await TryUpdateModelAsync<City>(
            cityToUpdate,
            "",
            i => i.CityName))
            {
                UpdateStadiumByCity(selectedStadiums, cityToUpdate);
                try
                {
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateException /* ex */)
                {

                    ModelState.AddModelError("", "Unable to save changes. " +
                    "Try again, and if the problem persists, ");
                }
                return RedirectToAction(nameof(Index));
            }
            UpdateStadiumByCity(selectedStadiums, cityToUpdate);
            PopulateCityStadiumData(cityToUpdate);
            return View(cityToUpdate);
        }
        private void UpdateStadiumByCity(string[] selectedStadiums, City cityToUpdate)
        {
            if (selectedStadiums == null)
            {
                cityToUpdate.StadiumByCity = new List<StadiumByCity>();
                return;
            }
            var selectedStadiumsHS = new HashSet<string>(selectedStadiums);
            var cityStadium = new HashSet<int>
            (cityToUpdate.StadiumByCity.Select(c => c.Stadium.ID));
            foreach (var stadium in _context.Stadiums)
            {
                if (selectedStadiumsHS.Contains(stadium.ID.ToString()))
                {
                    if (!cityStadium.Contains(stadium.ID))
                    {
                        cityToUpdate.StadiumByCity.Add(new StadiumByCity
                        {
                            CityID =cityToUpdate.ID,
                            StadiumID = stadium.ID
                        });
                    }
                }
                else
                {
                    if (cityStadium.Contains(stadium.ID))
                    {
                        StadiumByCity stadiumToRemove = cityToUpdate.StadiumByCity.FirstOrDefault(i
                       => i.StadiumID == stadium.ID);
                        _context.Remove(stadiumToRemove);
                    }
                }
            }
        }


        // GET: Cities/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.City_1 == null)
            {
                return NotFound();
            }

            var city = await _context.City_1
                .FirstOrDefaultAsync(m => m.ID == id);
            if (city == null)
            {
                return NotFound();
            }

            return View(city);
        }

        // POST: Cities/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.City_1 == null)
            {
                return Problem("Entity set 'LibraryContext.City_1'  is null.");
            }
            var city = await _context.City_1.FindAsync(id);
            if (city != null)
            {
                _context.City_1.Remove(city);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CityExists(int id)
        {
          return _context.City_1.Any(e => e.ID == id);
        }
    }
}

MPA_Project_Juca_Oana/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Football Arena Tours</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MPA_Project_Juca_Oana.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Football Arena Tours</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Stadiums" asp-action="Index">Stadiums</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cities" asp-action="Index">Cities</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Statistics">Statistics</a>
                            </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Chat">Chat</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MPA_Project_Juca_Oana - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>